export const SET_DARK_MODE = 'SET_DARK_MODE'
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS'
export const SET_WEB3 = 'SET_WEB3'
export const INIT = 'INIT'
